sudo: required
language: node_js
node_js:
  - "6.9.1"
cache:
  directories:
    - node_modules # NPM packages
install:
  - npm install
  - npm install gitbook
#  - sudo pip install awscli
script:
#  - gitbook install
#  - gitbook build ./ docs/
  - npm run docs:build
  # If the build is not a PR and is on the source branch, deploy the GitBook to S3.
  # CLI cloudfront invalidation is still in preview: http://docs.aws.amazon.com/cli/latest/reference/cloudfront/create-invalidation.html
#  - | 
#      if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "source" ]]; then
#        aws s3 sync --acl public-read --delete _book/ s3://rusoto.org ;
#        aws configure set preview.cloudfront true ;
#        aws cloudfront create-invalidation --distribution-id E1LZO76WJHQFTB --paths "/*";
#      else
#        echo "conditions not right for publish"
#      fi
branches:
  only:
    - source
    - auto

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: gh-pages

notifications:
  email: false
