sudo: required
language: node_js
node_js:
  - "6.9.1"
cache:
  directories:
    - node_modules # NPM packages

install:
  - npm install
  - npm install gitbook
  - npm install gitbook-cli
script:
  - npm run docs:build

branches:
  only:
    - source
    - auto

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
#  target-branch: gh-pages
  on:
    branch: source
#  repo: takuti/takuti.github.io
#  target_branch: master
#  fqdn: takuti.me
  local-dir: "_book"
  verbose: true

notifications:
  email: false
