dist: trusty
language: node_js
sudo: required
notifications:
  email: false

branches:
  only:
    - source
    - auto

node_js:
  - "6.9.1"

cache:
  directories:
    - node_modules # NPM packages


######################
before_install:

install:

before_deploy:

deploy:

