dist: trusty
language: node_js
sudo: required
notifications:
  email: false

branches:
  only:
    - source
    - auto

node_js:
  - "6.9.1"

cache:
  directories:
    - node_modules # NPM packages


######################
before_install:
  - npm install gitbook
  - npm install gitbook-cli

install:
  - gitbook install
  - gitbook build
  - ls -lha

before_deploy:
  - |
    echo "Starting to update gh-pages\n"
    cp -R _book $HOME/_book
    
    #go to home and setup git
    cd $HOME
    git config --global user.email "travis@travis-ci.org"
    git config --global user.name "Travis"
    
    #using token clone gh-pages branch
    git clone --quiet --branch=gh-pages https://${GH_TOKEN}@github.com/${GH_USER}/${GH_REPO}.git gh-pages > /dev/null
    
    #go into directory and copy data we're interested in to that directory
    cd gh-pages
    cp -Rf $HOME/_book/* .    
    


deploy:
  - |
    cd $HOME
    git add -f .
    git commit -m "Travis build $TRAVIS_BUILD_NUMBER"
    git push -fq origin gh-pages > /dev/null


