dist: trusty

sudo: required
language: node_js
node_js:
#  - "6.9.1"
  - "stable"
cache:
  directories:
    - node_modules # NPM packages

before_install:
  - sudo apt-get update -qq

install:
  - npm install
  - npm install gitbook
  - npm install gitbook-cli
script:
  - ls -lha
  - npm run docs:build
  - git add *
  - ls -lha

branches:
  only:
    - source
    - auto

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: source
  repo: dtnpnk/docs-gitbook
#  target_branch: master
#  fqdn: takuti.me
#  local-dir: "_book"
  verbose: true

notifications:
  email: false
